form{"action":"test/updateTest","clonable":true}
	fieldset
		legend:"BLA"
		field
			label:"Name"
			input
	field{"clonable":true}
		label:"Name"
		input
	field
		label:"Name"
		input{"clonable":true}
	field.buttons
		button.p5{"type":"submit"}:"Submit"
