-- MySQL Script generated by MySQL Workbench
-- Thu Sep 20 19:53:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `cms_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cms_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `status` TINYINT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `cms_role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cms_role_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_roles1_idx` (`cms_role_id` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`cms_role_id`)
    REFERENCES `cms_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `path` VARCHAR(255) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC));


-- -----------------------------------------------------
-- Table `cms_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action` TEXT NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  `ua` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `cms_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cms_user_id`),
  INDEX `fk_logs_users1_idx` (`cms_user_id` ASC),
  CONSTRAINT `fk_logs_users1`
    FOREIGN KEY (`cms_user_id`)
    REFERENCES `cms_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cms_views`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_views` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cms_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `value` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cms_role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_role_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cms_role_id` INT NOT NULL,
  `cms_view_id` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `cms_role_id`, `cms_view_id`),
  INDEX `fk_cms_role_permissions_cms_roles1_idx` (`cms_role_id` ASC),
  INDEX `fk_cms_role_permissions_cms_views1_idx` (`cms_view_id` ASC),
  CONSTRAINT `fk_cms_role_permissions_cms_roles1`
    FOREIGN KEY (`cms_role_id`)
    REFERENCES `cms_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cms_role_permissions_cms_views1`
    FOREIGN KEY (`cms_view_id`)
    REFERENCES `cms_views` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
